services:
  check-ins:
    build:
      context: check-ins
      dockerfile: CheckIns.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      check-ins-db-1:
        condition: service_healthy
    networks:
      - kavuny-net

  check-ins-db-1:
    build:
      context: check-ins
      dockerfile: Cassandra.Dockerfile
    networks:
      - kavuny-net
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 15s
      timeout: 20s
      retries: 3
      start_period: 20s
  # check-ins-db-2:
  #   image: cassandra:latest
  #   networks:
  #     - kavuny-net
  #   environment:
  #     - CASSANDRA_SEEDS=check-ins-db-1
  #   depends_on:
  #     check-ins-db-1:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD-SHELL", "nodetool status | grep UN"]
  #     interval: 15s
  #     timeout: 20s
  #     retries: 3
  #     start_period: 20s

networks:
  kavuny-net:
    driver: bridge