on:
  push:
    branches:
      - main

jobs:
  compose-up:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "./compose.yaml"
